CREATE TABLE AGENCIA (
    ID_AGENCIA INTEGER,
    NOMBRE VARCHAR2(50),
	PAIS VARCHAR2(50),
	FECHA_FUNDACION DATE,
	AUTOR_EXAMEN VARCHAR2(50),
	CONSTRAINT PK_AGENCIA PRIMARY KEY (ID_AGENCIA),
	CONSTRAINT NN_AGENCIA_NOMBRE CHECK (NOMBRE IS NOT NULL),
	CONSTRAINT NN_AGENCIA_PAIS CHECK (PAIS IS NOT NULL),
	CONSTRAINT NN_AGENCIA_FECHA_FUNDACION CHECK (FECHA_FUNDACION IS NOT NULL),
	CONSTRAINT NN_AGENCIA_AUTOR_EXAMEN CHECK (AUTOR_EXAMEN IS NOT NULL)	
);


CREATE TABLE SATELITE (
    ID_SATELITE INTEGER,
    NOMBRE VARCHAR2(50),
	ORBITA VARCHAR2(10),
	PESO DECIMAL(20, 2),,
	COSTE DECIMAL(20, 2),,
	ACTIVO VARCHAR2(10),
	FECHA_LANZAMIENTO DATE,
	ID_AGENCIA INTEGER,
	AUTOR_EXAMEN VARCHAR2(50),
	CONSTRAINT PK_SATELITE PRIMARY KEY (ID_SATELITE),
	CONSTRAINT FK_SATELITE_AGENCIA FOREIGN KEY (ID_AGENCIA) REFERENCES AGENCIA(ID_AGENCIA),
	CONSTRAINT CK_SATELITE_ACTIVO CHECK (ACTIVO IN ('ACTIVO', 'INACTIVO')),
	CONSTRAINT CK_SATELITE_ORBITA CHECK (ORBITA IN ('ALTA', 'MEDIA', 'BAJA')),
	CONSTRAINT NN_SATELITE_NOMBRE CHECK (NOMBRE IS NOT NULL),
	CONSTRAINT NN_SATELITE_ORBITA CHECK (ORBITA IS NOT NULL),
	CONSTRAINT NN_SATELITE_PESO CHECK (PESO IS NOT NULL),
	CONSTRAINT NN_SATELITE_COSTE CHECK (COSTE IS NOT NULL),
	CONSTRAINT NN_SATELITE_ACTIVO CHECK (ACTIVO IS NOT NULL),
	CONSTRAINT NN_SATELITE_FECHA_LANZAMIENTO CHECK (FECHA_LANZAMIENTO IS NOT NULL),
	CONSTRAINT NN_SATELITE_ID_AGENCIA CHECK (ID_AGENCIA IS NOT NULL),
	CONSTRAINT NN_SATELITE_AUTOR_EXAMEN CHECK (AUTOR_EXAMEN IS NOT NULL)
);

	
CREATE TABLE DETALLE_SATELITE (
    ID_DETALLE_SATELITE INTEGER,
    VELOCIDAD_MAXIMA VARCHAR2(50),
	COMBUSTIBLE VARCHAR2(50),
	VIDA_UTIL VARCHAR2(50),
	TEMPERATURA_MAXIMA NUMBER(20, 2),
	ID_SATELITE INTEGER,
	AUTOR_EXAMEN VARCHAR2(50),
	CONSTRAINT PK_DETALLE_SATELITE PRIMARY KEY (ID_DETALLE_SATELITE),
	CONSTRAINT FK_DETALLE_SATELITE_ID_SATELITE FOREIGN KEY (ID_SATELITE) REFERENCES SATELITE(ID_SATELITE),
	CONSTRAINT UQ_DETALLE_SATELITE_ID_SATELITE UNIQUE (ID_SATELITE),
	CONSTRAINT NN_DETALLE_SATELITE_VELOCIDAD_MAXIMA CHECK (VELOCIDAD_MAXIMA IS NOT NULL),
	CONSTRAINT NN_DETALLE_SATELITE_COMBUSTIBLE CHECK (COMBUSTIBLE IS NOT NULL),	
	CONSTRAINT NN_DETALLE_SATELITE_VIDA_UTIL CHECK (VIDA_UTIL IS NOT NULL),	
	CONSTRAINT NN_DETALLE_SATELITE_TEMPERATURA_MAXIMA CHECK (TEMPERATURA_MAXIMA IS NOT NULL),	
	CONSTRAINT NN_DETALLE_SATELITE_ID_SATELITE CHECK (ID_SATELITE IS NOT NULL),	
	CONSTRAINT NN_DETALLE_SATELITE_AUTOR_EXAMEN CHECK (AUTOR_EXAMEN IS NOT NULL)
);	
	
